import { mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import { runInit } from '../src/commands/init'
import { CONFIG_FILE } from '../src/core/constants'

describe('runInit', () => {
  it('writes baseline config and utility files', async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), 'fictcn-init-'))
    await writeFile(path.join(cwd, 'package.json'), '{"name":"sandbox"}\n', 'utf8')
    await writeFile(path.join(cwd, 'tsconfig.json'), '{"compilerOptions":{}}\n', 'utf8')

    await runInit({ cwd, skipInstall: true })

    const config = await readFile(path.join(cwd, CONFIG_FILE), 'utf8')
    const cnFile = await readFile(path.join(cwd, 'src/lib/cn.ts'), 'utf8')
    const globals = await readFile(path.join(cwd, 'src/styles/globals.css'), 'utf8')
    const postcss = await readFile(path.join(cwd, 'postcss.config.mjs'), 'utf8')
    const tsconfig = await readFile(path.join(cwd, 'tsconfig.json'), 'utf8')

    expect(config).toContain('"style": "tailwind-css-vars"')
    expect(cnFile).toContain('twMerge')
    expect(globals).toContain('@fictcn tokens:start')
    expect(postcss).toContain("'@tailwindcss/postcss'")
    expect(postcss).not.toContain('tailwindcss: {}')
    expect(tsconfig).toContain('"@/*"')
  })

  it('preserves existing config values on re-init', async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), 'fictcn-init-existing-'))
    await writeFile(path.join(cwd, 'package.json'), '{"name":"sandbox"}\n', 'utf8')
    await writeFile(path.join(cwd, 'tsconfig.json'), '{"compilerOptions":{}}\n', 'utf8')
    await writeFile(
      path.join(cwd, CONFIG_FILE),
      `${JSON.stringify(
        {
          $schema: 'https://fict.js.org/schemas/fictcn.schema.json',
          version: 1,
          style: 'tailwind-css-vars',
          componentsDir: 'custom/ui',
          libDir: 'custom/lib',
          css: 'custom/styles.css',
          tailwindConfig: 'tailwind.custom.ts',
          registry: 'builtin',
          aliases: {
            base: '~',
          },
        },
        null,
        2,
      )}\n`,
      'utf8',
    )

    await runInit({ cwd, skipInstall: true })

    const config = await readFile(path.join(cwd, CONFIG_FILE), 'utf8')
    const cnFile = await readFile(path.join(cwd, 'custom/lib/cn.ts'), 'utf8')
    const globals = await readFile(path.join(cwd, 'custom/styles.css'), 'utf8')
    const tailwindConfig = await readFile(path.join(cwd, 'tailwind.custom.ts'), 'utf8')
    const tsconfig = await readFile(path.join(cwd, 'tsconfig.json'), 'utf8')

    expect(config).toContain('"componentsDir": "custom/ui"')
    expect(config).toContain('"aliases": {\n    "base": "~"\n  }')
    expect(cnFile).toContain('twMerge')
    expect(globals).toContain('@fictcn tokens:start')
    expect(tailwindConfig).toContain('tailwindcss-animate')
    expect(tailwindConfig).not.toContain("'./src/**/*.{ts,tsx}'")
    expect(tailwindConfig).toContain("'./custom/ui/**/*.{ts,tsx}'")
    expect(tailwindConfig).toContain("'./custom/blocks/**/*.{ts,tsx}'")
    expect(tailwindConfig).toContain("'./custom/lib/**/*.{ts,tsx}'")
    expect(tsconfig).toContain('"~/*"')
    expect(tsconfig).toContain('"*"')
  })

  it('patches tsconfig JSONC with comments and trailing commas', async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), 'fictcn-init-jsonc-'))
    await writeFile(path.join(cwd, 'package.json'), '{"name":"sandbox"}\n', 'utf8')
    await writeFile(
      path.join(cwd, 'tsconfig.json'),
      `{
  // generated by tsc --init
  "compilerOptions": {
    "target": "ES2022",
  },
}
`,
      'utf8',
    )

    await runInit({ cwd, skipInstall: true })

    const tsconfig = await readFile(path.join(cwd, 'tsconfig.json'), 'utf8')
    expect(tsconfig).toContain('"@/*"')
    expect(tsconfig).toContain('"src/*"')
  })

  it('patches CommonJS tailwind config without injecting ESM syntax', async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), 'fictcn-init-tailwind-cjs-'))
    await writeFile(path.join(cwd, 'package.json'), '{"name":"sandbox"}\n', 'utf8')
    await writeFile(path.join(cwd, 'tsconfig.json'), '{"compilerOptions":{}}\n', 'utf8')
    await writeFile(
      path.join(cwd, CONFIG_FILE),
      `${JSON.stringify(
        {
          $schema: 'https://fict.js.org/schemas/fictcn.schema.json',
          version: 1,
          style: 'tailwind-css-vars',
          componentsDir: 'src/components/ui',
          libDir: 'src/lib',
          css: 'src/styles/globals.css',
          tailwindConfig: 'tailwind.config.cjs',
          registry: 'builtin',
          aliases: {
            base: '@',
          },
        },
        null,
        2,
      )}\n`,
      'utf8',
    )
    await writeFile(
      path.join(cwd, 'tailwind.config.cjs'),
      "module.exports = { content: ['./src/**/*.{ts,tsx}'], theme: { extend: {} }, plugins: [] }\n",
      'utf8',
    )

    await runInit({ cwd, skipInstall: true })

    const tailwindConfig = await readFile(path.join(cwd, 'tailwind.config.cjs'), 'utf8')
    expect(tailwindConfig).toContain('module.exports')
    expect(tailwindConfig).toContain("require('tailwindcss-animate')")
    expect(tailwindConfig).not.toContain("import animate from 'tailwindcss-animate'")
    expect(tailwindConfig).toContain("'./src/components/ui/**/*.{ts,tsx}'")
  })

  it('creates CommonJS tailwind config for .js when package type is commonjs', async () => {
    const cwd = await mkdtemp(path.join(tmpdir(), 'fictcn-init-tailwind-js-cjs-'))
    await writeFile(
      path.join(cwd, 'package.json'),
      '{"name":"sandbox","type":"commonjs"}\n',
      'utf8',
    )
    await writeFile(path.join(cwd, 'tsconfig.json'), '{"compilerOptions":{}}\n', 'utf8')
    await writeFile(
      path.join(cwd, CONFIG_FILE),
      `${JSON.stringify(
        {
          $schema: 'https://fict.js.org/schemas/fictcn.schema.json',
          version: 1,
          style: 'tailwind-css-vars',
          componentsDir: 'src/components/ui',
          libDir: 'src/lib',
          css: 'src/styles/globals.css',
          tailwindConfig: 'tailwind.config.js',
          registry: 'builtin',
          aliases: {
            base: '@',
          },
        },
        null,
        2,
      )}\n`,
      'utf8',
    )

    await runInit({ cwd, skipInstall: true })

    const tailwindConfig = await readFile(path.join(cwd, 'tailwind.config.js'), 'utf8')
    expect(tailwindConfig).toContain('module.exports = config')
    expect(tailwindConfig).toContain("require('tailwindcss-animate')")
    expect(tailwindConfig).not.toContain("import animate from 'tailwindcss-animate'")
  })
})
