/**
 * Example datasets mirrored from the React shadcn/ui v4 site.
 *
 * dashboardTableRows matches app/(app)/examples/dashboard/data.json,
 * taskRows matches app/(app)/examples/tasks/data/tasks.json, and
 * visitorChartData matches the inline series in chart-area-interactive.tsx.
 */

export interface DashboardTableRow {
  id: number
  header: string
  type: string
  status: string
  target: string
  limit: string
  reviewer: string
}

export interface TaskRow {
  id: string
  title: string
  status: string
  label: string
  priority: string
}

export interface VisitorPoint {
  date: string
  desktop: number
  mobile: number
}

export const dashboardTableRows: DashboardTableRow[] = [
  { id: 1, header: "Cover page", type: "Cover page", status: "In Process", target: "18", limit: "5", reviewer: "Eddie Lake" },
  { id: 2, header: "Table of contents", type: "Table of contents", status: "Done", target: "29", limit: "24", reviewer: "Eddie Lake" },
  { id: 3, header: "Executive summary", type: "Narrative", status: "Done", target: "10", limit: "13", reviewer: "Eddie Lake" },
  { id: 4, header: "Technical approach", type: "Narrative", status: "Done", target: "27", limit: "23", reviewer: "Jamik Tashpulatov" },
  { id: 5, header: "Design", type: "Narrative", status: "In Process", target: "2", limit: "16", reviewer: "Jamik Tashpulatov" },
  { id: 6, header: "Capabilities", type: "Narrative", status: "In Process", target: "20", limit: "8", reviewer: "Jamik Tashpulatov" },
  { id: 7, header: "Integration with existing systems", type: "Narrative", status: "In Process", target: "19", limit: "21", reviewer: "Jamik Tashpulatov" },
  { id: 8, header: "Innovation and Advantages", type: "Narrative", status: "Done", target: "25", limit: "26", reviewer: "Assign reviewer" },
  { id: 9, header: "Overview of EMR's Innovative Solutions", type: "Technical content", status: "Done", target: "7", limit: "23", reviewer: "Assign reviewer" },
  { id: 10, header: "Advanced Algorithms and Machine Learning", type: "Narrative", status: "Done", target: "30", limit: "28", reviewer: "Assign reviewer" },
  { id: 11, header: "Adaptive Communication Protocols", type: "Narrative", status: "Done", target: "9", limit: "31", reviewer: "Assign reviewer" },
  { id: 12, header: "Advantages Over Current Technologies", type: "Narrative", status: "Done", target: "12", limit: "0", reviewer: "Assign reviewer" },
  { id: 13, header: "Past Performance", type: "Narrative", status: "Done", target: "22", limit: "33", reviewer: "Assign reviewer" },
  { id: 14, header: "Customer Feedback and Satisfaction Levels", type: "Narrative", status: "Done", target: "15", limit: "34", reviewer: "Assign reviewer" },
  { id: 15, header: "Implementation Challenges and Solutions", type: "Narrative", status: "Done", target: "3", limit: "35", reviewer: "Assign reviewer" },
  { id: 16, header: "Security Measures and Data Protection Policies", type: "Narrative", status: "In Process", target: "6", limit: "36", reviewer: "Assign reviewer" },
  { id: 17, header: "Scalability and Future Proofing", type: "Narrative", status: "Done", target: "4", limit: "37", reviewer: "Assign reviewer" },
  { id: 18, header: "Cost-Benefit Analysis", type: "Plain language", status: "Done", target: "14", limit: "38", reviewer: "Assign reviewer" },
  { id: 19, header: "User Training and Onboarding Experience", type: "Narrative", status: "Done", target: "17", limit: "39", reviewer: "Assign reviewer" },
  { id: 20, header: "Future Development Roadmap", type: "Narrative", status: "Done", target: "11", limit: "40", reviewer: "Assign reviewer" },
  { id: 21, header: "System Architecture Overview", type: "Technical content", status: "In Process", target: "24", limit: "18", reviewer: "Maya Johnson" },
  { id: 22, header: "Risk Management Plan", type: "Narrative", status: "Done", target: "15", limit: "22", reviewer: "Carlos Rodriguez" },
  { id: 23, header: "Compliance Documentation", type: "Legal", status: "In Process", target: "31", limit: "27", reviewer: "Sarah Chen" },
  { id: 24, header: "API Documentation", type: "Technical content", status: "Done", target: "8", limit: "12", reviewer: "Raj Patel" },
  { id: 25, header: "User Interface Mockups", type: "Visual", status: "In Process", target: "19", limit: "25", reviewer: "Leila Ahmadi" },
  { id: 26, header: "Database Schema", type: "Technical content", status: "Done", target: "22", limit: "20", reviewer: "Thomas Wilson" },
  { id: 27, header: "Testing Methodology", type: "Technical content", status: "In Process", target: "17", limit: "14", reviewer: "Assign reviewer" },
  { id: 28, header: "Deployment Strategy", type: "Narrative", status: "Done", target: "26", limit: "30", reviewer: "Eddie Lake" },
  { id: 29, header: "Budget Breakdown", type: "Financial", status: "In Process", target: "13", limit: "16", reviewer: "Jamik Tashpulatov" },
  { id: 30, header: "Market Analysis", type: "Research", status: "Done", target: "29", limit: "32", reviewer: "Sophia Martinez" },
  { id: 31, header: "Competitor Comparison", type: "Research", status: "In Process", target: "21", limit: "19", reviewer: "Assign reviewer" },
  { id: 32, header: "Maintenance Plan", type: "Technical content", status: "Done", target: "16", limit: "23", reviewer: "Alex Thompson" },
  { id: 33, header: "User Personas", type: "Research", status: "In Process", target: "27", limit: "24", reviewer: "Nina Patel" },
  { id: 34, header: "Accessibility Compliance", type: "Legal", status: "Done", target: "18", limit: "21", reviewer: "Assign reviewer" },
  { id: 35, header: "Performance Metrics", type: "Technical content", status: "In Process", target: "23", limit: "26", reviewer: "David Kim" },
  { id: 36, header: "Disaster Recovery Plan", type: "Technical content", status: "Done", target: "14", limit: "17", reviewer: "Jamik Tashpulatov" },
  { id: 37, header: "Third-party Integrations", type: "Technical content", status: "In Process", target: "25", limit: "28", reviewer: "Eddie Lake" },
  { id: 38, header: "User Feedback Summary", type: "Research", status: "Done", target: "20", limit: "15", reviewer: "Assign reviewer" },
  { id: 39, header: "Localization Strategy", type: "Narrative", status: "In Process", target: "12", limit: "19", reviewer: "Maria Garcia" },
  { id: 40, header: "Mobile Compatibility", type: "Technical content", status: "Done", target: "28", limit: "31", reviewer: "James Wilson" },
  { id: 41, header: "Data Migration Plan", type: "Technical content", status: "In Process", target: "19", limit: "22", reviewer: "Assign reviewer" },
  { id: 42, header: "Quality Assurance Protocols", type: "Technical content", status: "Done", target: "30", limit: "33", reviewer: "Priya Singh" },
  { id: 43, header: "Stakeholder Analysis", type: "Research", status: "In Process", target: "11", limit: "14", reviewer: "Eddie Lake" },
  { id: 44, header: "Environmental Impact Assessment", type: "Research", status: "Done", target: "24", limit: "27", reviewer: "Assign reviewer" },
  { id: 45, header: "Intellectual Property Rights", type: "Legal", status: "In Process", target: "17", limit: "20", reviewer: "Sarah Johnson" },
  { id: 46, header: "Customer Support Framework", type: "Narrative", status: "Done", target: "22", limit: "25", reviewer: "Jamik Tashpulatov" },
  { id: 47, header: "Version Control Strategy", type: "Technical content", status: "In Process", target: "15", limit: "18", reviewer: "Assign reviewer" },
  { id: 48, header: "Continuous Integration Pipeline", type: "Technical content", status: "Done", target: "26", limit: "29", reviewer: "Michael Chen" },
  { id: 49, header: "Regulatory Compliance", type: "Legal", status: "In Process", target: "13", limit: "16", reviewer: "Assign reviewer" },
  { id: 50, header: "User Authentication System", type: "Technical content", status: "Done", target: "28", limit: "31", reviewer: "Eddie Lake" },
  { id: 51, header: "Data Analytics Framework", type: "Technical content", status: "In Process", target: "21", limit: "24", reviewer: "Jamik Tashpulatov" },
  { id: 52, header: "Cloud Infrastructure", type: "Technical content", status: "Done", target: "16", limit: "19", reviewer: "Assign reviewer" },
  { id: 53, header: "Network Security Measures", type: "Technical content", status: "In Process", target: "29", limit: "32", reviewer: "Lisa Wong" },
  { id: 54, header: "Project Timeline", type: "Planning", status: "Done", target: "14", limit: "17", reviewer: "Eddie Lake" },
  { id: 55, header: "Resource Allocation", type: "Planning", status: "In Process", target: "27", limit: "30", reviewer: "Assign reviewer" },
  { id: 56, header: "Team Structure and Roles", type: "Planning", status: "Done", target: "20", limit: "23", reviewer: "Jamik Tashpulatov" },
  { id: 57, header: "Communication Protocols", type: "Planning", status: "In Process", target: "15", limit: "18", reviewer: "Assign reviewer" },
  { id: 58, header: "Success Metrics", type: "Planning", status: "Done", target: "30", limit: "33", reviewer: "Eddie Lake" },
  { id: 59, header: "Internationalization Support", type: "Technical content", status: "In Process", target: "23", limit: "26", reviewer: "Jamik Tashpulatov" },
  { id: 60, header: "Backup and Recovery Procedures", type: "Technical content", status: "Done", target: "18", limit: "21", reviewer: "Assign reviewer" },
  { id: 61, header: "Monitoring and Alerting System", type: "Technical content", status: "In Process", target: "25", limit: "28", reviewer: "Daniel Park" },
  { id: 62, header: "Code Review Guidelines", type: "Technical content", status: "Done", target: "12", limit: "15", reviewer: "Eddie Lake" },
  { id: 63, header: "Documentation Standards", type: "Technical content", status: "In Process", target: "27", limit: "30", reviewer: "Jamik Tashpulatov" },
  { id: 64, header: "Release Management Process", type: "Planning", status: "Done", target: "22", limit: "25", reviewer: "Assign reviewer" },
  { id: 65, header: "Feature Prioritization Matrix", type: "Planning", status: "In Process", target: "19", limit: "22", reviewer: "Emma Davis" },
  { id: 66, header: "Technical Debt Assessment", type: "Technical content", status: "Done", target: "24", limit: "27", reviewer: "Eddie Lake" },
  { id: 67, header: "Capacity Planning", type: "Planning", status: "In Process", target: "21", limit: "24", reviewer: "Jamik Tashpulatov" },
  { id: 68, header: "Service Level Agreements", type: "Legal", status: "Done", target: "26", limit: "29", reviewer: "Assign reviewer" },
]

export const taskRows: TaskRow[] = [
  { id: "TASK-8782", title: "You can't compress the program without quantifying the open-source SSD pixel!", status: "in progress", label: "documentation", priority: "medium" },
  { id: "TASK-7878", title: "Try to calculate the EXE feed, maybe it will index the multi-byte pixel!", status: "backlog", label: "documentation", priority: "medium" },
  { id: "TASK-7839", title: "We need to bypass the neural TCP card!", status: "todo", label: "bug", priority: "high" },
  { id: "TASK-5562", title: "The SAS interface is down, bypass the open-source pixel so we can back up the PNG bandwidth!", status: "backlog", label: "feature", priority: "medium" },
  { id: "TASK-8686", title: "I'll parse the wireless SSL protocol, that should driver the API panel!", status: "canceled", label: "feature", priority: "medium" },
  { id: "TASK-1280", title: "Use the digital TLS panel, then you can transmit the haptic system!", status: "done", label: "bug", priority: "high" },
  { id: "TASK-7262", title: "The UTF8 application is down, parse the neural bandwidth so we can back up the PNG firewall!", status: "done", label: "feature", priority: "high" },
  { id: "TASK-1138", title: "Generating the driver won't do anything, we need to quantify the 1080p SMTP bandwidth!", status: "in progress", label: "feature", priority: "medium" },
  { id: "TASK-7184", title: "We need to program the back-end THX pixel!", status: "todo", label: "feature", priority: "low" },
  { id: "TASK-5160", title: "Calculating the bus won't do anything, we need to navigate the back-end JSON protocol!", status: "in progress", label: "documentation", priority: "high" },
  { id: "TASK-5618", title: "Generating the driver won't do anything, we need to index the online SSL application!", status: "done", label: "documentation", priority: "medium" },
  { id: "TASK-6699", title: "I'll transmit the wireless JBOD capacitor, that should hard drive the SSD feed!", status: "backlog", label: "documentation", priority: "medium" },
  { id: "TASK-2858", title: "We need to override the online UDP bus!", status: "backlog", label: "bug", priority: "medium" },
  { id: "TASK-9864", title: "I'll reboot the 1080p FTP panel, that should matrix the HEX hard drive!", status: "done", label: "bug", priority: "high" },
  { id: "TASK-8404", title: "We need to generate the virtual HEX alarm!", status: "in progress", label: "bug", priority: "low" },
  { id: "TASK-5365", title: "Backing up the pixel won't do anything, we need to transmit the primary IB array!", status: "in progress", label: "documentation", priority: "low" },
  { id: "TASK-1780", title: "The CSS feed is down, index the bluetooth transmitter so we can compress the CLI protocol!", status: "todo", label: "documentation", priority: "high" },
  { id: "TASK-6938", title: "Use the redundant SCSI application, then you can hack the optical alarm!", status: "todo", label: "documentation", priority: "high" },
  { id: "TASK-9885", title: "We need to compress the auxiliary VGA driver!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-3216", title: "Transmitting the transmitter won't do anything, we need to compress the virtual HDD sensor!", status: "backlog", label: "documentation", priority: "medium" },
  { id: "TASK-9285", title: "The IP monitor is down, copy the haptic alarm so we can generate the HTTP transmitter!", status: "todo", label: "bug", priority: "high" },
  { id: "TASK-1024", title: "Overriding the microchip won't do anything, we need to transmit the digital OCR transmitter!", status: "in progress", label: "documentation", priority: "low" },
  { id: "TASK-7068", title: "You can't generate the capacitor without indexing the wireless HEX pixel!", status: "canceled", label: "bug", priority: "low" },
  { id: "TASK-6502", title: "Navigating the microchip won't do anything, we need to bypass the back-end SQL bus!", status: "todo", label: "bug", priority: "high" },
  { id: "TASK-5326", title: "We need to hack the redundant UTF8 transmitter!", status: "todo", label: "bug", priority: "low" },
  { id: "TASK-6274", title: "Use the virtual PCI circuit, then you can parse the bluetooth alarm!", status: "canceled", label: "documentation", priority: "low" },
  { id: "TASK-1571", title: "I'll input the neural DRAM circuit, that should protocol the SMTP interface!", status: "in progress", label: "feature", priority: "medium" },
  { id: "TASK-9518", title: "Compressing the interface won't do anything, we need to compress the online SDD matrix!", status: "canceled", label: "documentation", priority: "medium" },
  { id: "TASK-5581", title: "I'll synthesize the digital COM pixel, that should transmitter the UTF8 protocol!", status: "backlog", label: "documentation", priority: "high" },
  { id: "TASK-2197", title: "Parsing the feed won't do anything, we need to copy the bluetooth DRAM bus!", status: "todo", label: "documentation", priority: "low" },
  { id: "TASK-8484", title: "We need to parse the solid state UDP firewall!", status: "in progress", label: "bug", priority: "low" },
  { id: "TASK-9892", title: "If we back up the application, we can get to the UDP application through the multi-byte THX capacitor!", status: "done", label: "documentation", priority: "high" },
  { id: "TASK-9616", title: "We need to synthesize the cross-platform ASCII pixel!", status: "in progress", label: "feature", priority: "medium" },
  { id: "TASK-9744", title: "Use the back-end IP card, then you can input the solid state hard drive!", status: "done", label: "documentation", priority: "low" },
  { id: "TASK-1376", title: "Generating the alarm won't do anything, we need to generate the mobile IP capacitor!", status: "backlog", label: "documentation", priority: "low" },
  { id: "TASK-7382", title: "If we back up the firewall, we can get to the RAM alarm through the primary UTF8 pixel!", status: "todo", label: "feature", priority: "low" },
  { id: "TASK-2290", title: "I'll compress the virtual JSON panel, that should application the UTF8 bus!", status: "canceled", label: "documentation", priority: "high" },
  { id: "TASK-1533", title: "You can't input the firewall without overriding the wireless TCP firewall!", status: "done", label: "bug", priority: "high" },
  { id: "TASK-4920", title: "Bypassing the hard drive won't do anything, we need to input the bluetooth JSON program!", status: "in progress", label: "bug", priority: "high" },
  { id: "TASK-5168", title: "If we synthesize the bus, we can get to the IP panel through the virtual TLS array!", status: "in progress", label: "feature", priority: "low" },
  { id: "TASK-7103", title: "We need to parse the multi-byte EXE bandwidth!", status: "canceled", label: "feature", priority: "low" },
  { id: "TASK-4314", title: "If we compress the program, we can get to the XML alarm through the multi-byte COM matrix!", status: "in progress", label: "bug", priority: "high" },
  { id: "TASK-3415", title: "Use the cross-platform XML application, then you can quantify the solid state feed!", status: "todo", label: "feature", priority: "high" },
  { id: "TASK-8339", title: "Try to calculate the DNS interface, maybe it will input the bluetooth capacitor!", status: "in progress", label: "feature", priority: "low" },
  { id: "TASK-6995", title: "Try to hack the XSS bandwidth, maybe it will override the bluetooth matrix!", status: "todo", label: "feature", priority: "high" },
  { id: "TASK-8053", title: "If we connect the program, we can get to the UTF8 matrix through the digital UDP protocol!", status: "todo", label: "feature", priority: "medium" },
  { id: "TASK-4336", title: "If we synthesize the microchip, we can get to the SAS sensor through the optical UDP program!", status: "todo", label: "documentation", priority: "low" },
  { id: "TASK-8790", title: "I'll back up the optical COM alarm, that should alarm the RSS capacitor!", status: "done", label: "bug", priority: "medium" },
  { id: "TASK-8980", title: "Try to navigate the SQL transmitter, maybe it will back up the virtual firewall!", status: "canceled", label: "bug", priority: "low" },
  { id: "TASK-7342", title: "Use the neural CLI card, then you can parse the online port!", status: "backlog", label: "documentation", priority: "low" },
  { id: "TASK-5608", title: "I'll hack the haptic SSL program, that should bus the UDP transmitter!", status: "canceled", label: "documentation", priority: "low" },
  { id: "TASK-1606", title: "I'll generate the bluetooth PNG firewall, that should pixel the SSL driver!", status: "done", label: "feature", priority: "medium" },
  { id: "TASK-7872", title: "Transmitting the circuit won't do anything, we need to reboot the 1080p RSS monitor!", status: "canceled", label: "feature", priority: "medium" },
  { id: "TASK-4167", title: "Use the cross-platform SMS circuit, then you can synthesize the optical feed!", status: "canceled", label: "bug", priority: "medium" },
  { id: "TASK-9581", title: "You can't index the port without hacking the cross-platform XSS monitor!", status: "backlog", label: "documentation", priority: "low" },
  { id: "TASK-8806", title: "We need to bypass the back-end SSL panel!", status: "done", label: "bug", priority: "medium" },
  { id: "TASK-6542", title: "Try to quantify the RSS firewall, maybe it will quantify the open-source system!", status: "done", label: "feature", priority: "low" },
  { id: "TASK-6806", title: "The VGA protocol is down, reboot the back-end matrix so we can parse the CSS panel!", status: "canceled", label: "documentation", priority: "low" },
  { id: "TASK-9549", title: "You can't bypass the bus without connecting the neural JBOD bus!", status: "todo", label: "feature", priority: "high" },
  { id: "TASK-1075", title: "Backing up the driver won't do anything, we need to parse the redundant RAM pixel!", status: "done", label: "feature", priority: "medium" },
  { id: "TASK-1427", title: "Use the auxiliary PCI circuit, then you can calculate the cross-platform interface!", status: "done", label: "documentation", priority: "high" },
  { id: "TASK-1907", title: "Hacking the circuit won't do anything, we need to back up the online DRAM system!", status: "todo", label: "documentation", priority: "high" },
  { id: "TASK-4309", title: "If we generate the system, we can get to the TCP sensor through the optical GB pixel!", status: "backlog", label: "bug", priority: "medium" },
  { id: "TASK-3973", title: "I'll parse the back-end ADP array, that should bandwidth the RSS bandwidth!", status: "todo", label: "feature", priority: "medium" },
  { id: "TASK-7962", title: "Use the wireless RAM program, then you can hack the cross-platform feed!", status: "canceled", label: "bug", priority: "low" },
  { id: "TASK-3360", title: "You can't quantify the program without synthesizing the neural OCR interface!", status: "done", label: "feature", priority: "medium" },
  { id: "TASK-9887", title: "Use the auxiliary ASCII sensor, then you can connect the solid state port!", status: "backlog", label: "bug", priority: "medium" },
  { id: "TASK-3649", title: "I'll input the virtual USB system, that should circuit the DNS monitor!", status: "in progress", label: "feature", priority: "medium" },
  { id: "TASK-3586", title: "If we quantify the circuit, we can get to the CLI feed through the mobile SMS hard drive!", status: "in progress", label: "bug", priority: "low" },
  { id: "TASK-5150", title: "I'll hack the wireless XSS port, that should transmitter the IP interface!", status: "canceled", label: "feature", priority: "medium" },
  { id: "TASK-3652", title: "The SQL interface is down, override the optical bus so we can program the ASCII interface!", status: "backlog", label: "feature", priority: "low" },
  { id: "TASK-6884", title: "Use the digital PCI circuit, then you can synthesize the multi-byte microchip!", status: "canceled", label: "feature", priority: "high" },
  { id: "TASK-1591", title: "We need to connect the mobile XSS driver!", status: "in progress", label: "feature", priority: "high" },
  { id: "TASK-3802", title: "Try to override the ASCII protocol, maybe it will parse the virtual matrix!", status: "in progress", label: "feature", priority: "low" },
  { id: "TASK-7253", title: "Programming the capacitor won't do anything, we need to bypass the neural IB hard drive!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-9739", title: "We need to hack the multi-byte HDD bus!", status: "done", label: "documentation", priority: "medium" },
  { id: "TASK-4424", title: "Try to hack the HEX alarm, maybe it will connect the optical pixel!", status: "in progress", label: "documentation", priority: "medium" },
  { id: "TASK-3922", title: "You can't back up the capacitor without generating the wireless PCI program!", status: "backlog", label: "bug", priority: "low" },
  { id: "TASK-4921", title: "I'll index the open-source IP feed, that should system the GB application!", status: "canceled", label: "bug", priority: "low" },
  { id: "TASK-5814", title: "We need to calculate the 1080p AGP feed!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-2645", title: "Synthesizing the system won't do anything, we need to navigate the multi-byte HDD firewall!", status: "todo", label: "documentation", priority: "medium" },
  { id: "TASK-4535", title: "Try to copy the JSON circuit, maybe it will connect the wireless feed!", status: "in progress", label: "feature", priority: "low" },
  { id: "TASK-4463", title: "We need to copy the solid state AGP monitor!", status: "done", label: "documentation", priority: "low" },
  { id: "TASK-9745", title: "If we connect the protocol, we can get to the GB system through the bluetooth PCI microchip!", status: "canceled", label: "feature", priority: "high" },
  { id: "TASK-2080", title: "If we input the bus, we can get to the RAM matrix through the auxiliary RAM card!", status: "todo", label: "bug", priority: "medium" },
  { id: "TASK-3838", title: "I'll bypass the online TCP application, that should panel the AGP system!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-1340", title: "We need to navigate the virtual PNG circuit!", status: "todo", label: "bug", priority: "medium" },
  { id: "TASK-6665", title: "If we parse the monitor, we can get to the SSD hard drive through the cross-platform AGP alarm!", status: "canceled", label: "feature", priority: "low" },
  { id: "TASK-7585", title: "If we calculate the hard drive, we can get to the SSL program through the multi-byte CSS microchip!", status: "backlog", label: "feature", priority: "low" },
  { id: "TASK-6319", title: "We need to copy the multi-byte SCSI program!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-4369", title: "Try to input the SCSI bus, maybe it will generate the 1080p pixel!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-9035", title: "We need to override the solid state PNG array!", status: "canceled", label: "documentation", priority: "low" },
  { id: "TASK-3970", title: "You can't index the transmitter without quantifying the haptic ASCII card!", status: "todo", label: "documentation", priority: "medium" },
  { id: "TASK-4473", title: "You can't bypass the protocol without overriding the neural RSS program!", status: "todo", label: "documentation", priority: "low" },
  { id: "TASK-4136", title: "You can't hack the hard drive without hacking the primary JSON program!", status: "canceled", label: "bug", priority: "medium" },
  { id: "TASK-3939", title: "Use the back-end SQL firewall, then you can connect the neural hard drive!", status: "done", label: "feature", priority: "low" },
  { id: "TASK-2007", title: "I'll input the back-end USB protocol, that should bandwidth the PCI system!", status: "backlog", label: "bug", priority: "high" },
  { id: "TASK-7516", title: "Use the primary SQL program, then you can generate the auxiliary transmitter!", status: "done", label: "documentation", priority: "medium" },
  { id: "TASK-6906", title: "Try to back up the DRAM system, maybe it will reboot the online transmitter!", status: "done", label: "feature", priority: "high" },
  { id: "TASK-5207", title: "The SMS interface is down, copy the bluetooth bus so we can quantify the VGA card!", status: "in progress", label: "bug", priority: "low" },
]

export const visitorChartData: VisitorPoint[] = [
  { date: "2024-04-01", desktop: 222, mobile: 150 },
  { date: "2024-04-02", desktop: 97, mobile: 180 },
  { date: "2024-04-03", desktop: 167, mobile: 120 },
  { date: "2024-04-04", desktop: 242, mobile: 260 },
  { date: "2024-04-05", desktop: 373, mobile: 290 },
  { date: "2024-04-06", desktop: 301, mobile: 340 },
  { date: "2024-04-07", desktop: 245, mobile: 180 },
  { date: "2024-04-08", desktop: 409, mobile: 320 },
  { date: "2024-04-09", desktop: 59, mobile: 110 },
  { date: "2024-04-10", desktop: 261, mobile: 190 },
  { date: "2024-04-11", desktop: 327, mobile: 350 },
  { date: "2024-04-12", desktop: 292, mobile: 210 },
  { date: "2024-04-13", desktop: 342, mobile: 380 },
  { date: "2024-04-14", desktop: 137, mobile: 220 },
  { date: "2024-04-15", desktop: 120, mobile: 170 },
  { date: "2024-04-16", desktop: 138, mobile: 190 },
  { date: "2024-04-17", desktop: 446, mobile: 360 },
  { date: "2024-04-18", desktop: 364, mobile: 410 },
  { date: "2024-04-19", desktop: 243, mobile: 180 },
  { date: "2024-04-20", desktop: 89, mobile: 150 },
  { date: "2024-04-21", desktop: 137, mobile: 200 },
  { date: "2024-04-22", desktop: 224, mobile: 170 },
  { date: "2024-04-23", desktop: 138, mobile: 230 },
  { date: "2024-04-24", desktop: 387, mobile: 290 },
  { date: "2024-04-25", desktop: 215, mobile: 250 },
  { date: "2024-04-26", desktop: 75, mobile: 130 },
  { date: "2024-04-27", desktop: 383, mobile: 420 },
  { date: "2024-04-28", desktop: 122, mobile: 180 },
  { date: "2024-04-29", desktop: 315, mobile: 240 },
  { date: "2024-04-30", desktop: 454, mobile: 380 },
  { date: "2024-05-01", desktop: 165, mobile: 220 },
  { date: "2024-05-02", desktop: 293, mobile: 310 },
  { date: "2024-05-03", desktop: 247, mobile: 190 },
  { date: "2024-05-04", desktop: 385, mobile: 420 },
  { date: "2024-05-05", desktop: 481, mobile: 390 },
  { date: "2024-05-06", desktop: 498, mobile: 520 },
  { date: "2024-05-07", desktop: 388, mobile: 300 },
  { date: "2024-05-08", desktop: 149, mobile: 210 },
  { date: "2024-05-09", desktop: 227, mobile: 180 },
  { date: "2024-05-10", desktop: 293, mobile: 330 },
  { date: "2024-05-11", desktop: 335, mobile: 270 },
  { date: "2024-05-12", desktop: 197, mobile: 240 },
  { date: "2024-05-13", desktop: 197, mobile: 160 },
  { date: "2024-05-14", desktop: 448, mobile: 490 },
  { date: "2024-05-15", desktop: 473, mobile: 380 },
  { date: "2024-05-16", desktop: 338, mobile: 400 },
  { date: "2024-05-17", desktop: 499, mobile: 420 },
  { date: "2024-05-18", desktop: 315, mobile: 350 },
  { date: "2024-05-19", desktop: 235, mobile: 180 },
  { date: "2024-05-20", desktop: 177, mobile: 230 },
  { date: "2024-05-21", desktop: 82, mobile: 140 },
  { date: "2024-05-22", desktop: 81, mobile: 120 },
  { date: "2024-05-23", desktop: 252, mobile: 290 },
  { date: "2024-05-24", desktop: 294, mobile: 220 },
  { date: "2024-05-25", desktop: 201, mobile: 250 },
  { date: "2024-05-26", desktop: 213, mobile: 170 },
  { date: "2024-05-27", desktop: 420, mobile: 460 },
  { date: "2024-05-28", desktop: 233, mobile: 190 },
  { date: "2024-05-29", desktop: 78, mobile: 130 },
  { date: "2024-05-30", desktop: 340, mobile: 280 },
  { date: "2024-05-31", desktop: 178, mobile: 230 },
  { date: "2024-06-01", desktop: 178, mobile: 200 },
  { date: "2024-06-02", desktop: 470, mobile: 410 },
  { date: "2024-06-03", desktop: 103, mobile: 160 },
  { date: "2024-06-04", desktop: 439, mobile: 380 },
  { date: "2024-06-05", desktop: 88, mobile: 140 },
  { date: "2024-06-06", desktop: 294, mobile: 250 },
  { date: "2024-06-07", desktop: 323, mobile: 370 },
  { date: "2024-06-08", desktop: 385, mobile: 320 },
  { date: "2024-06-09", desktop: 438, mobile: 480 },
  { date: "2024-06-10", desktop: 155, mobile: 200 },
  { date: "2024-06-11", desktop: 92, mobile: 150 },
  { date: "2024-06-12", desktop: 492, mobile: 420 },
  { date: "2024-06-13", desktop: 81, mobile: 130 },
  { date: "2024-06-14", desktop: 426, mobile: 380 },
  { date: "2024-06-15", desktop: 307, mobile: 350 },
  { date: "2024-06-16", desktop: 371, mobile: 310 },
  { date: "2024-06-17", desktop: 475, mobile: 520 },
  { date: "2024-06-18", desktop: 107, mobile: 170 },
  { date: "2024-06-19", desktop: 341, mobile: 290 },
  { date: "2024-06-20", desktop: 408, mobile: 450 },
  { date: "2024-06-21", desktop: 169, mobile: 210 },
  { date: "2024-06-22", desktop: 317, mobile: 270 },
  { date: "2024-06-23", desktop: 480, mobile: 530 },
  { date: "2024-06-24", desktop: 132, mobile: 180 },
  { date: "2024-06-25", desktop: 141, mobile: 190 },
  { date: "2024-06-26", desktop: 434, mobile: 380 },
  { date: "2024-06-27", desktop: 448, mobile: 490 },
  { date: "2024-06-28", desktop: 149, mobile: 200 },
  { date: "2024-06-29", desktop: 103, mobile: 160 },
  { date: "2024-06-30", desktop: 446, mobile: 400 },
]
